### ISSUE TITLE
Current Alpha Artifact seems to have erased Crafting Manager NBT data

### ISSUE THREAD

**Issue by Souliboi** [Delfayne/LogisticsBridge#13]
When loading up a World with preconfigured Crafting Managers with the ["wait for result"](https://github.com/Delfayne/LogisticsBridge/actions/runs/5171781717) build artifacts for example, loading the latest ["1.5.0-alpha-ab4c-780"](https://github.com/Delfayne/LogisticsBridge/actions/runs/5184534607) seems to have fully erased all of it.
![image](https://github.com/Delfayne/LogisticsBridge/assets/106060704/c6bcdf41-669b-4780-95d6-82cb5ea2533c)

**Comment by KorewaLidesu** [comment]
~~Make sure you did not download old version :dumb:~~

~~I will make new GHA to separating stuff out~~ #14 
 
Please check https://github.com/Delfayne/LogisticsBridge/actions/runs/5203309119

**Comment by Souliboi** [comment]
It seems that using the Build you linked to crashes the client when trying it in FTB Interactions during boot time.
![image](https://github.com/Delfayne/LogisticsBridge/assets/106060704/c8146d0d-a07b-4404-b190-7f5310d139ef)

---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 2023-06-08 18:04:47 CEST
Description: Initializing game

java.lang.IllegalAccessError: tried to access class org.spongepowered.asm.mixin.transformer.MixinProcessor from class net.minecraftforge.fml.common.Loader
    at net.minecraftforge.fml.common.Loader.handler$zzb000$VanillaFix_1_0_10_150$beforeConstructingMods(Loader.java:1141)
    at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:594)
    at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:232)
    at net.minecraft.client.Minecraft.init(Minecraft.java:467)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3931)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243)
    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278)
    at org.multimc.EntryPoint.listen(EntryPoint.java:143)
    at org.multimc.EntryPoint.main(EntryPoint.java:34)

Full report here:
[crash-2023-06-08_18.04.47-client.txt](https://github.com/Delfayne/LogisticsBridge/files/11690786/crash-2023-06-08_18.04.47-client.txt)

Forge version is 14.23.5.2860
Spark and Morph-o-Tool, which were added as some tryout mods also have been removed with the same result

Using GraalVM-EE Java 8 21.3.5 with these Arguments as well if that's relevant
`-XX:+UnlockExperimentalVMOptions -XX:+UnlockDiagnosticVMOptions -XX:+AlwaysActAsServerClassMachine -XX:+AlwaysPreTouch -XX:+DisableExplicitGC -XX:+UseNUMA -XX:AllocatePrefetchStyle=3 -XX:NmethodSweepActivity=1 -XX:ReservedCodeCacheSize=400M -XX:-DontCompileHugeMethods -XX:+PerfDisableSharedMem -XX:+UseFastUnorderedTimeStamps -XX:+UseCriticalJavaThreadPriority -XX:+EagerJVMCI -Dgraal.TuneInlinerExploration=1 -Dgraal.CompilerConfiguration=enterprise -XX:+UseG1GC -XX:MaxGCPauseMillis=37 -XX:+PerfDisableSharedMem -XX:G1HeapRegionSize=16M -XX:G1NewSizePercent=23 -XX:G1ReservePercent=20 -XX:SurvivorRatio=32 -XX:G1MixedGCCountTarget=3 -XX:G1HeapWastePercent=20 -XX:InitiatingHeapOccupancyPercent=10 -XX:G1RSetUpdatingPauseTimePercent=0 -XX:MaxTenuringThreshold=1 -XX:G1SATBBufferEnqueueingThresholdPercent=30 -XX:G1ConcMarkStepDurationMillis=5.0 -XX:G1ConcRSHotCardLimit=16 -XX:G1ConcRefinementServiceIntervalMillis=150 -XX:GCTimeRatio=99`

**Comment by KorewaLidesu** [comment]
Disable / Remove VanillaFix for now
Tracking https://github.com/LoliKingdom/MixinBooter/issues/34

**Comment by Souliboi** [comment]
Unless VanillaFix has dependencies which I am unaware off, removing it [causes this crash.](https://paste.ee/p/FHc6a)
[Gist Link of the snippet](https://gist.github.com/SoulMH/19db8a6819f05948fd007a0377f5d11d)
[crash-2023-06-08_18.34.13-client.txt](https://github.com/Delfayne/LogisticsBridge/files/11690994/crash-2023-06-08_18.34.13-client.txt)

**Comment by KorewaLidesu** [comment]
Remove Phosphor, use Hesperus instead
https://www.curseforge.com/minecraft/mc-mods/hesperus

Also, please put the snippet to Gist or something else instead

**Comment by Souliboi** [comment]
Pack loaded up fine with all the changes now done.
Issue with the provided build persists, tested on a known good backup from last year in FTB Interactions.
![image](https://github.com/Delfayne/LogisticsBridge/assets/106060704/1ed1a7e2-bd2d-424a-a9cc-1fa6d92214ff)

On the upside, nothing aside from that seems to have broken during the loading process of a world that used the provided versions of LP and LB that FTB Interactions currently ships with.

**Comment by KorewaLidesu** [comment]
Thanks for the info
I will take look at it
Is this happen when Gui close, or only on world reload?

**Comment by Souliboi** [comment]
This happens when the world is loaded for the first time and no more beyond that

**Comment by KorewaLidesu** [comment]
> This happens when the world is loaded for the first time and no more beyond that

So this only happen when load from old save then
Can you send me the old save?

**Comment by Souliboi** [comment]
From an old save and generally any world before the build linked in the original post as I've tried it on my current world (screenshot in OP) and the backup.
[Old Backup here](https://cdn.discordapp.com/attachments/1060447937487978557/1116414903629139989/2022-06-10-16-10-12.zip)

**Comment by Souliboi** [comment]
Build from the pull request appeared to fix the issue
